namespace ChatClient
{
    internal class ResponseStore
    {
        public class AUTH
        {
            public const string LOGIN = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=MTNiODE0OWItNjdlYi00NjMxLTkzZDItNGUwOTdkYjFkNjIx; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 08:50:53 GMT\r\nConnection: close\r\n\r\n62\r\n{\"id\":2,\"firstName\":\"Petrov\",\"lastName\":\"Petr\",\"roles\":[\"USER\",\"ADMIN\"],\"email\":\"admin@gmai.com\"}\r\n";

            public const string REGISTER = "HTTP/1.1 201 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=OTNlNGJhNDctYWJjNC00NWNjLWI4NDMtNDMxMWM3ODRmMDli; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 08:57:30 GMT\r\nConnection: close\r\n\r\n5c\r\n{\"id\":3,\"firstName\":\"Vasiliev\",\"lastName\":\"Petr\",\"roles\":[\"USER\"],\"email\":\"vasya@gmail.com\"}\r\n";

            public const string LOGOUT = "HTTP/1.1 200 \r\nSet-Cookie: JSESSIONID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Path=/\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 08:53:47 GMT\r\n\r\n";

            public const string USER_INFO = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=Mjg1YWM5Y2ItYTg3MS00YjZlLWE2NzAtYWNmMDNhZWE4ZTE0; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 09:09:09 GMT\r\nConnection: close\r\n\r\n62\r\n{\"id\":2,\"firstName\":\"Petrov\",\"lastName\":\"Petr\",\"roles\":[\"USER\",\"ADMIN\"],\"email\":\"admin@gmail.com\"}\r\n";
        }

        public class ACCOUNT
        {
            public const string SEARCH_ACCOUNT = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=MzA0MjMxZjktOTg4My00YTdmLWI1MmUtNTAzNWZjMDBjM2M5; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 09:17:02 GMT\r\n\r\n5b\r\n[{\"id\":1,\"firstName\":\"Ivanov\",\"lastName\":\"Ivan\",\"roles\":[\"USER\"],\"email\":\"user@gmail.com\"}]\r\n";

            public const string UPDATE_ACCOUNT = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=NjJkYzJmYmItNGRhYi00ZWFiLTg5MzktZmZjMGM1OGM5Mjc5; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 10:02:35 GMT\r\nConnection: close\r\n\r\n5d\r\n{\"id\":4,\"firstName\":\"Valerya\",\"lastName\":\"Sidorov\",\"roles\":[\"USER\"],\"email\":\"demo@gmail.com\"}\r\n";

            public const string REMOVE_ACCOUNT = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=ZGVmYWNhN2EtY2Y2ZS00Yjc1LWExZjEtMDU1ZmE3M2M5Yjcz; Path=/; HttpOnly; SameSite=Lax\r\nContent-Length: 0\r\nDate: Tue, 07 Mar 2023 10:13:26 GMT\r\n\r\n";

            public const string GET_ROLES_FOR_USER_BY_ID = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=ZTNhNWYxMDgtNWUzZS00NDgxLTgxMzUtZmQwOGRhNzkzZGNk; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 10:09:28 GMT\r\n\r\n8\r\n[\"USER\"]\r\n";

            public const string ADD_ROLE_FOR_ACCOUNT = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=YjliMjM3MjgtMThiNi00Y2UzLWJhOTUtNTMwMDU2ZGI2NDQ1; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 10:10:41 GMT\r\n\r\n65\r\n{\"id\":4,\"firstName\":\"Valerya\",\"lastName\":\"Sidorov\",\"roles\":[\"USER\",\"ADMIN\"],\"email\":\"demo@gmail.com\"}\r\n";

            public const string REMOVE_ROLE_FOR_ACCOUNT = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=YWQ1NmQ3NjEtOWEzNi00OWVkLWE0MzgtYjJiZGNjOTZjOWM1; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 10:12:11 GMT\r\n\r\n5d\r\n{\"id\":4,\"firstName\":\"Valerya\",\"lastName\":\"Sidorov\",\"roles\":[\"USER\"],\"email\":\"demo@gmail.com\"}\r\n";
        }

        public class MESSAGES
        {
            public const string SEARH_MESSAGE = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=YjRiMTZlOTktNGU0Zi00Nzk2LTg2NDEtYjQwY2U4ZDkzMjdl; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 10:15:57 GMT\r\n\r\nb1\r\n[{\"id\":2,\"senderUsername\":\"admin@gmail.com\",\"receiverUsername\":\"user@gmail.com\",\"messageText\":\"hi, Ivan\",\"creationTime\":\"2021-12-31T21:00:00.000+00:00\",\"modificationTime\":null}]\r\n";

            public const string GET_MESSAGE_BY_ID = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=OTUxYjEyODEtNTFkOC00OGYwLTg5ODktZTlhMzk4ZGQ4NzE2; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 10:17:26 GMT\r\n\r\naf\r\n{\"id\":2,\"senderUsername\":\"admin@gmail.com\",\"receiverUsername\":\"user@gmail.com\",\"messageText\":\"hi, Ivan\",\"creationTime\":\"2021-12-31T21:00:00.000+00:00\",\"modificationTime\":null}\r\n";

            public const string SEND_MESSAGE = "HTTP/1.1 201 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=MDMzNzdmZTUtYThjNS00NWVlLTljNzQtNzRiODVlNzQwYzdi; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 10:19:02 GMT\r\n\r\nb4\r\n{\"id\":6,\"senderUsername\":\"admin@gmail.com\",\"receiverUsername\":\"user@gmail.com\",\"messageText\":\"wassup my boy\",\"creationTime\":\"2023-03-07T10:19:02.813+00:00\",\"modificationTime\":null}\r\n";

            public const string UPDATE_MESSAGE = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=YTU0MzcwN2UtZmRiYi00MzQ1LWI2MzQtM2QwYmVmZGNmZjYz; Path=/; HttpOnly; SameSite=Lax\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nDate: Tue, 07 Mar 2023 10:20:34 GMT\r\nConnection: close\r\n\r\nd2\r\n{\"id\":6,\"senderUsername\":\"admin@gmail.com\",\"receiverUsername\":\"user@gmail.com\",\"messageText\":\"new text message\",\"creationTime\":\"2023-03-06T21:00:00.000+00:00\",\"modificationTime\":\"2023-03-07T10:20:34.965+00:00\"}\r\n";

            public const string REMOVE_MESSAGE = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=Mzk0NWE2OGEtNzE4Ni00ZjMwLThjY2EtMzUwYTgyNWFkMGRh; Path=/; HttpOnly; SameSite=Lax\r\nContent-Length: 0\r\nDate: Tue, 07 Mar 2023 10:21:44 GMT\r\n\r\n";

            public const string REMOVE_SEVERAL_MESSAGES = "HTTP/1.1 200 \r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache\r\nExpires: 0\r\nX-Frame-Options: DENY\r\nSet-Cookie: SESSION=NzlkNTU5MTEtNDc5Yy00OTRjLTk4MTktMjI4ZjY2ZWIzNzBj; Path=/; HttpOnly; SameSite=Lax\r\nContent-Length: 0\r\nDate: Tue, 07 Mar 2023 10:23:17 GMT\r\nConnection: close\r\n\r\n";
        }
    }
}